* Basic Setup
** Lexical binding
#+begin_src emacs-lisp
  ;; -*- lexical-binding: t; -*-
#+end_src
** Custom file Location
- Do not modify init.el.
#+begin_src emacs-lisp
  (setq custom-file "~/.emacs.d/.emacs-custom.el")
  (load custom-file t t)
#+end_src

** My Info
#+begin_src emacs-lisp
  (setq user-full-name "Ayush Singh"
        user-mail-address "ayushsingh1325@gmail.com")
#+end_src
** Auto-save
- Create auto-save files in /tmp
#+begin_src emacs-lisp
  (setq backup-directory-alist
        `((".*" . ,temporary-file-directory)))
  (setq auto-save-file-name-transforms
        `((".*" ,temporary-file-directory t)))
#+end_src
** IDO
#+begin_src emacs-lisp
  (setq ido-enable-flex-matching t)
  (ido-mode 1)
  (ido-everywhere 1)
#+end_src

** Line Numbers
#+begin_src emacs-lisp
  (setq-default display-line-numbers-type 'relative)
  (global-display-line-numbers-mode 1)
#+end_src

** Spellcheck
#+begin_src emacs-lisp
  (setq ispell-program-name "hunspell"
        ispell-dictionary "en_IN")
#+end_src
** Refresh files
- Mainly for notes
#+begin_src emacs-lisp
  (global-auto-revert-mode 1)
#+end_src

** Columns
- Hard wrap at 100 cols
#+begin_src emacs-lisp
  (setq-default fill-column 100)
  (add-hook 'text-mode-hook #'auto-fill-mode)
#+end_src
- Show col number in modline
#+begin_src emacs-lisp
  (column-number-mode 1)
  (setq column-number-indicator-zero-based nil)  ; 1-based columns, like Vim
#+end_src

** Auto save
#+begin_src emacs-lisp
  (setq auto-save-visited-interval 60)   ; seconds of idle time before saving
  (auto-save-visited-mode 1)
#+end_src

* Packaging
** Packaging
- use-package is built in (Emacs 29+). Only used for packages that aren't.
#+begin_src emacs-lisp
  (require 'package)
#+end_src
** MELPA
#+begin_src emacs-lisp
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
#+end_src

* Ui
** Menus stuff
- Disable toolbar
#+begin_src emacs-lisp
  (tool-bar-mode -1)
#+end_src
- Disable Menu Bar
#+begin_src emacs-lisp
  (menu-bar-mode -1)
#+end_src
- Disable scrollbar
#+begin_src emacs-lisp
  (scroll-bar-mode -1)
#+end_src
- Shorten prompt answers
#+begin_src emacs-lisp
  (fset 'yes-or-no-p 'y-or-n-p)
#+end_src
** Remove startpage
#+begin_src emacs-lisp
  (setq inhibit-startup-screen t)
#+end_src
** Which Key
- Built in since Emacs 30
#+begin_src emacs-lisp
  (which-key-mode)
#+end_src
** Theme
#+begin_src emacs-lisp
  (use-package dracula-theme
    :ensure t
    :config
    (load-theme 'dracula t))
#+end_src
** Better buffer nav
#+begin_src emacs-lisp
  (windmove-default-keybindings)
#+end_src

** Font
#+begin_src emacs-lisp
  (set-face-attribute 'default nil :family "JetBrainsMono Nerd Font" :height 140 :weight 'medium)
#+end_src

** Better completion
- Vertical completion for some commands.
#+begin_src emacs-lisp
  (fido-vertical-mode 1)
#+end_src
- When fido-vertical-mode is being used, hide the normal completions
#+begin_src emacs-lisp
  (with-eval-after-load 'icomplete
    (define-key icomplete-fido-mode-map (kbd "TAB") #'icomplete-force-complete))
#+end_src

** Modeline
#+begin_src emacs-lisp
  (use-package doom-modeline
    :ensure t
    :init (doom-modeline-mode 1))
#+end_src

* Evil
** Basic
#+begin_src emacs-lisp
  (use-package evil
    :ensure t
    :init
    (setq evil-want-keybinding nil)
    (setq evil-want-minibuffer t)
    :config
    (evil-mode 1)
    (setq which-key-allow-evil-operators t)
    (evil-set-leader '(normal visual motion) (kbd "SPC"))
    (setq evil-undo-system 'undo-redo))
#+end_src

** Evil collection
#+begin_src emacs-lisp
  (use-package evil-collection
    :ensure t
    :after evil
    :config
    (evil-collection-init))
#+end_src

** Basic keybindings
*** Nice keymps
#+begin_src emacs-lisp
  ;; In evil's :config, right after evil-set-leader and BEFORE any <leader> bindings
  (dolist (prefix '(("b" . "buffer-prefix")
  		  ("f" . "files-prefix")
                    ("n" . "notes-prefix")
                    ("h" . "help-prefix")
                    ("m" . "mail-prefix")))
    (evil-define-key '(normal visual motion) 'global
      (kbd (concat "<leader>" (car prefix)))
      (cons (cdr prefix) (make-sparse-keymap))))
#+end_src

*** File/buffer related
#+begin_src emacs-lisp
  (evil-define-key '(normal visual motion) 'global
    ;; files and buffers, matching your Neovim setup
    (kbd "<leader>ff") #'find-file
    (kbd "<leader>fb") #'switch-to-buffer
    (kbd "<leader>bb") #'switch-to-buffer
    (kbd "<leader>bi") #'ibuffer
    (kbd "<leader>bk") #'kill-buffer
    (kbd "<leader>bd") #'kill-current-buffer)
#+end_src

*** Help
#+begin_src emacs-lisp
  (evil-define-key '(normal visual motion) 'global
    (kbd "<leader>hf") #'describe-function
    (kbd "<leader>hv") #'describe-variable
    (kbd "<leader>hk") #'describe-key
    (kbd "<leader>hm") #'describe-mode
    (kbd "<leader>ho") #'describe-symbol)
#+end_src

*** Calendar
#+begin_src emacs-lisp
  (evil-define-key 'normal 'global
    (kbd "<leader>c") #'calendar)
#+end_src

* Gnus
** Accounts
*** Disable NNTP. Not using it
#+begin_src emacs-lisp
  (setq gnus-select-method '(nnnil ""))
#+end_src
*** Set up mail boxes. Route expired emails into trash (default is Archive).
#+begin_src emacs-lisp
  (setq gnus-secondary-select-methods
        '((nnimap "personal"
                  (nnimap-user "ayushsingh1325@gmail.com")
                  (nnimap-address "imap.gmail.com")
                  (nnimap-server-port 993)
                  (nnimap-stream tls)
                  (nnmail-expiry-target "nnimap+personal:[Gmail]/Trash"))
          (nnimap "work"
                  (nnimap-user "ayush@beagleboard.org")
                  (nnimap-address "imap.gmail.com")
                  (nnimap-server-port 993)
                  (nnimap-stream tls)
                  (nnmail-expiry-target "nnimap+work:[Gmail]/Trash"))
          (nnimap "dev"
                  (nnimap-user "ayushdevel1325@gmail.com")
                  (nnimap-address "imap.gmail.com")
                  (nnimap-server-port 993)
                  (nnimap-stream tls)
                  (nnmail-expiry-target "nnimap+dev:[Gmail]/Trash"))
          (nnimap "banking"
                  (nnimap-user "ayushcreator1325@gmail.com")
                  (nnimap-address "imap.gmail.com")
                  (nnimap-server-port 993)
                  (nnimap-stream tls)
                  (nnmail-expiry-target "nnimap+banking:[Gmail]/Trash"))
          (nnimap "college"
                  (nnimap-user "20je0239@am.iitism.ac.in")
                  (nnimap-address "imap.gmail.com")
                  (nnimap-server-port 993)
                  (nnimap-stream tls)
                  (nnmail-expiry-target "nnimap+college:[Gmail]/Trash"))))
#+end_src
*** Configure SMTP for sending email
#+begin_src emacs-lisp
  (setq message-send-mail-function 'smtpmail-send-it
        smtpmail-smtp-server "smtp.gmail.com"
        smtpmail-smtp-service 587
        smtpmail-stream-type 'starttls)
#+end_src
*** Select correct smtp server based on FROM email
#+begin_src emacs-lisp
  (setq message-server-alist
        '(("ayushsingh1325@gmail.com"   . "smtp smtp.gmail.com 587 ayushsingh1325@gmail.com starttls")
          ("ayush@beagleboard.org"      . "smtp smtp.gmail.com 587 ayush@beagleboard.org starttls")
          ("ayushdevel1325@gmail.com"   . "smtp smtp.gmail.com 587 ayushdevel1325@gmail.com starttls")
          ("ayushcreator1325@gmail.com" . "smtp smtp.gmail.com 587 ayushcreator1325@gmail.com starttls")
          ("20je0239@am.iitism.ac.in"   . "smtp smtp.gmail.com 587 20je0239@am.iitism.ac.in starttls")))
#+end_src
*** Automatically use correct FROM email in replies
#+begin_src emacs-lisp
  (setq message-alternative-emails
        (regexp-opt '("ayushsingh1325@gmail.com"
                      "ayush@beagleboard.org"
                      "ayushdevel1325@gmail.com"
                      "ayushcreator1325@gmail.com"
                      "20je0239@am.iitism.ac.in")))
#+end_src
*** Use correct email when replying in mailing list
#+begin_src emacs-lisp
  (setq gnus-posting-styles
        '(("^nnimap\\+personal:" (address "ayushsingh1325@gmail.com"))
          ("^nnimap\\+work:"     (address "ayush@beagleboard.org")
  	                       (signature "BeagleBoard.org Foundation\nhttps://www.beagleboard.org"))
          ("^nnimap\\+dev:"      (address "ayushdevel1325@gmail.com"))
          ("^nnimap\\+banking:"  (address "ayushcreator1325@gmail.com"))
          ("^nnimap\\+college:"  (address "20je0239@am.iitism.ac.in"))))
#+end_src

*** Signoff
- Add signoff to all outgoing emails
#+begin_src emacs-lisp
  (defun my/message-insert-signoff ()
    "Add a sign-off before the signature, or at the end if there is none."
    (save-excursion
      (goto-char (point-max))
      (if (re-search-backward message-signature-separator nil t)
          (goto-char (match-beginning 0))   ; start of the "-- " line
        (goto-char (point-max)))
      (insert "\nBest Regards,\nAyush Singh\n\n")))

  (add-hook 'message-setup-hook #'my/message-insert-signoff)
#+end_src

** RSS
#+begin_src emacs-lisp
  (add-to-list 'gnus-secondary-select-methods
               '(nnatom "blog.rust-lang.org/feed.xml"))
#+end_src

** Sane defaults
- Article prefetch.
#+begin_src emacs-lisp
  (setq gnus-asynchronous t)
#+end_src
- Use Gmail default handling for sent mail.
#+begin_src emacs-lisp
  (setq gnus-message-archive-group nil)
#+end_src
- Better logging
#+begin_src emacs-lisp
  (setq nnimap-record-commands t)
#+end_src
- Auto-wrap
#+begin_src emacs-lisp
  (setq message-fill-column 75)
#+end_src
- Better expiry
#+begin_src emacs-lisp
  (setq nnmail-expiry-wait 'immediate)
  (setq nnmail-expunge 'on-exit)
#+end_src
- Turn on spellcheck for email composition
#+begin_src emacs-lisp
  (add-hook 'message-mode-hook #'turn-on-flyspell)
#+end_src

** Threads
- Show the whole thread when you enter one
#+begin_src emacs-lisp
  (setq gnus-fetch-old-headers 'some)
#+end_src
- I hate reading un-threaded email -- especially mailing lists.  This helps a ton!
#+begin_src emacs-lisp
  (setq gnus-summary-thread-gathering-function 'gnus-gather-threads-by-subject)
#+end_src
- Sort threads by most recent activity
#+begin_src emacs-lisp
  (setq gnus-thread-sort-functions
        '(gnus-thread-sort-by-most-recent-date))
#+end_src
- Only show top-level messages in threads
#+begin_src emacs-lisp
  (setq gnus-thread-hide-subtree t)
  (setq gnus-thread-ignore-subject t)
#+end_src

** Disable pinentry
- Flatpak emacs was failing
#+begin_src emacs-lisp
  (setq epg-pinentry-mode 'loopback)
#+end_src
** Autofetch
- Give up on a dead connection instead of hanging indefinitely
#+begin_src emacs-lisp
  (setq nnimap-connection-timeout 10)
#+end_src
- Scan for new mail every 5 minutes, but only when Emacs has been idle for 1 minute — so it doesn't freeze you mid-edit.
- Deferred until Gnus loads, so Gnus isn't pulled in at startup.
#+begin_src emacs-lisp
  (with-eval-after-load 'gnus
    (require 'gnus-demon)
    (gnus-demon-add-handler 'gnus-demon-scan-news 5 1)
    (gnus-demon-add-handler 'gnus-demon-close-connections 60 nil))
  (add-hook 'gnus-started-hook #'gnus-demon-init)
#+end_src
** Default email client
- Make gnus default
#+begin_src emacs-lisp
  (setopt
     mail-user-agent 'gnus-user-agent
     read-mail-command #'gnus)
#+end_src

** Pretty
- Enable topics
#+begin_src emacs-lisp
  (add-hook 'gnus-group-mode-hook 'gnus-topic-mode)
#+end_src
- Shorter names since topic name is already shown
#+begin_src emacs-lisp
  (setq gnus-group-line-format "%M%S%p%P%5y  %B%(%c%)\n"
        gnus-group-uncollapsed-levels 2)
#+end_src
- Better email summary line
#+begin_src emacs-lisp
  (setq gnus-summary-line-format
        "%U%R%z %&user-date;  %-20,20f  %B%s\n")
#+end_src

** Better Spam
- Add bindings to add/remove from spam
#+begin_src emacs-lisp
  (defun my/gnus-move-to-folder (folder)
    "Move current (or process-marked) articles to FOLDER on this group's server."
    (let ((group (or gnus-newsgroup-name "")))
      (if (string-match "\\`\\(nnimap\\+[^:]+\\):" group)
          (gnus-summary-move-article nil (concat (match-string 1 group) ":" folder))
        (user-error "Not an nnimap group"))))

  (defun my/gnus-mark-spam ()
    "Move article(s) to this account's Spam folder."
    (interactive)
    (my/gnus-move-to-folder "[Gmail]/Spam"))

  (defun my/gnus-mark-not-spam ()
    "Move article(s) out of Spam into this account's INBOX."
    (interactive)
    (my/gnus-move-to-folder "INBOX"))

  (with-eval-after-load 'gnus-sum
    (evil-define-key 'normal gnus-summary-mode-map
      (kbd "s") #'my/gnus-mark-spam
      (kbd "S") #'my/gnus-mark-not-spam))
#+end_src

** Notifications
- Show new email notifications.
#+begin_src emacs-lisp
  (add-hook 'gnus-after-getting-new-news-hook #'gnus-notifications)
#+end_src

** Keybindings
*** Rebind SPC
- Launch binding.
#+begin_src emacs-lisp
  (evil-define-key '(normal visual motion) 'global
    (kbd "<leader>mm") #'gnus             ; open Gnus
    (kbd "<leader>mc") #'compose-mail)    ; write a new message from anywhere
#+end_src

- I want to use SPC as leader key
#+begin_src emacs-lisp
  (with-eval-after-load 'gnus-group
    (evil-define-key '(normal motion) gnus-group-mode-map
      (kbd "RET") #'gnus-group-read-group
      (kbd "SPC") #'evil-send-leader))

  (with-eval-after-load 'gnus-sum
    (evil-define-key '(normal motion) gnus-summary-mode-map
      (kbd "RET") #'gnus-summary-next-page
      (kbd "SPC") #'evil-send-leader))
#+end_src
** Graceful Shutdonw
#+begin_src emacs-lisp
  (add-hook 'kill-emacs-hook
            (lambda ()
              (when (and (fboundp 'gnus-alive-p) (gnus-alive-p))
                (gnus-group-save-newsrc))))
#+end_src

* Org Mode
** Useful shortcuts
#+begin_src emacs-lisp
  (require 'org-tempo)
#+end_src
** Pretty bullets
#+begin_src emacs-lisp
  (use-package org-bullets
    :ensure t
    :hook (org-mode . org-bullets-mode))
#+end_src
** Better startup
#+begin_src emacs-lisp
  (setq org-startup-indented t)
  (setq org-startup-folded 'content)
#+end_src

** Agenda
#+begin_src emacs-lisp
  (setq org-agenda-start-with-log-mode t)
#+end_src
*** Record time when marking done
#+begin_src emacs-lisp
  (setq org-log-done 'time)
  (setq org-log-into-drawer t)
#+end_src

*** States
- Add WAITING (when waiting on input from others) and CANCELLED states.
- Add QUESTION/ANSWERED flow for doubts.
#+begin_src emacs-lisp
  (setq org-todo-keywords
        '((sequence "TODO(t)" "IN-PROGRESS(p@)" "|" "DONE(d!)" "CANCELLED(c@)")
  	(sequence "QUESTION(q)" "|" "ANSWERED(a@)")))
#+end_src

*** Keybiding for all tasks
#+begin_src emacs-lisp
  (defun my/org-agenda-todos ()
    "Open the custom \"T\" org agenda view."
    (interactive)
    (org-agenda nil "T"))

  (evil-define-key '(normal visual motion) 'global
    (kbd "<leader>na") #'my/org-agenda-todos)
#+end_src

** Google Calendar
#+begin_src emacs-lisp
  (use-package org-gcal
    :ensure t
    :init
    (when-let* ((entry (car (auth-source-search :host "org-gcal" :max 1))))
      (setq org-gcal-client-id (plist-get entry :user)
            org-gcal-client-secret (let ((s (plist-get entry :secret)))
                                     (if (functionp s) (funcall s) s))))
    (setq plstore-encrypt-to "05CEF5C789E55A74")
    (setq org-gcal-fetch-file-alist
        (let ((dir (expand-file-name "calendars/" user-emacs-directory)))
  	(make-directory dir t)
          `(("ayush@beagleboard.org" . ,(expand-file-name "work.org" dir)))))
    (with-eval-after-load 'denote-agenda
      (dolist (pair org-gcal-fetch-file-alist)
        (add-to-list 'denote-agenda-static-files (cdr pair))))
    :config
    ;; fetch a minute after startup
    (run-with-timer 60 nil #'org-gcal-fetch))
#+end_src

** Babble
- Use lexical bindings by default
#+begin_src emacs-lisp
  (setq org-babel-default-header-args:emacs-lisp
        '((:lexical . "yes")))
#+end_src

* Denote
** Basic setup
#+begin_src emacs-lisp
  (use-package denote
    :ensure t
    :hook (dired-mode . denote-dired-mode)
    :init
    (evil-define-key '(normal visual motion) 'global
      (kbd "<leader>nn") #'denote-open-or-create
      (kbd "<leader>nR") #'denote-rename-file-using-front-matter
      (kbd "<leader>nl") #'denote-link
      (kbd "<leader>nb") #'denote-backlinks
      (kbd "<leader>nd") #'denote-dired
      (kbd "<leader>ng") #'denote-grep)
    :config
    (setq denote-directory (expand-file-name "~/Documents/Notes/"))
    (setq denote-known-keywords '("projects" "misc"))

    ;; Automatically rename Denote buffers when opening them so that
    ;; instead of their long file name they have, for example, a literal
    ;; "[D]" followed by the file's title.  Read the docstring of
    ;; `denote-rename-buffer-format' for how to modify this.
    (denote-rename-buffer-mode 1)
    (setq denote-infer-keywords t)
    (setq denote-sort-keywords t)
    ;; Pick dates, where relevant, with Org's advanced interface:
    (setq denote-date-prompt-use-org-read-date t))
#+end_src

** Journal
*** Template
#+begin_src emacs-lisp
  (defun my/denote-journal-insert-template ()
    "Insert the default sections into a new journal entry."
    (goto-char (point-max))
    (insert "* BeagleBoard\n\n* Other\n"))
#+end_src

*** Setup
#+begin_src emacs-lisp
  (use-package denote-journal
    :ensure t
    :hook (calendar-mode . denote-journal-calendar-mode)
    :init
    (evil-define-key '(normal visual motion) 'global
      (kbd "<leader>nj") #'denote-journal-new-or-existing-entry)
    :config
    (setq denote-journal-directory
          (expand-file-name "journal" denote-directory))
    (setq denote-journal-keyword "journal")
    (setq denote-journal-title-format 'day-date-month-year)
    (add-hook 'denote-journal-hook #'my/denote-journal-insert-template))
#+end_src

*** Calendar integration
#+begin_src emacs-lisp
  (with-eval-after-load 'calendar
    (evil-define-key 'normal calendar-mode-map
      (kbd "RET") #'denote-journal-calendar-new-or-existing)
    (add-hook 'calendar-mode-hook #'denote-journal-calendar-mode))
#+end_src

** Agenda
- Org-agenda integration
#+begin_src emacs-lisp
  (use-package denote-agenda
    :ensure t
    :custom
    (denote-agenda-include-regexp "\\.org\\'")
    (denote-agenda-exclude-regexp "_journal")
    (denote-agenda-include-journal t)
    :config
    (denote-agenda-insinuate))
#+end_src

** Scatch
- A static note to store rudementary ideas.
#+begin_src emacs-lisp
  (defun my/open-scratch-note ()
    "Open the scratch note."
    (interactive)
    (require 'denote)
    (find-file (expand-file-name "scratch.org" denote-directory)))

  (with-eval-after-load 'org
    (add-to-list 'org-agenda-files (expand-file-name "scratch.org" denote-directory)))

  (evil-define-key '(normal visual motion) 'global
    (kbd "<leader>ns") #'my/open-scratch-note)
#+end_src

** Trash
- Move files to trash on delete.
#+begin_src emacs-lisp
  (setq delete-by-moving-to-trash 1)
#+end_src
* Programming
** Elisp
*** Eldoc
- eldoc shows a nice function signature in echo area.
#+begin_src emacs-lisp
  (add-hook 'emacs-lisp-mode-hook 'eldoc-mode)
  (add-hook 'lisp-interaction-mode-hook 'eldoc-mode)
  (add-hook 'ielm-mode-hook 'eldoc-mode)
  (add-hook 'emacs-lisp-mode-hook #'completion-preview-mode)
#+end_src

** Git
#+begin_src emacs-lisp
  (use-package magit
    :ensure t)

  (evil-define-key 'normal 'global (kbd "<leader>gg") #'magit-status)
#+end_src

* Helpers
** Github Link to Title
- Mainly for daily journaling. Will take a Github PR link and create a line for format "{PR Title}: {URL}"
#+begin_src emacs-lisp
  (defun my/gh/issue-or-pull-title (owner repo num callback)
    "Fetch the title of issue or pull request NUM in OWNER/REPO asynchronously.
  Call CALLBACK with the title as a valid string if it succeeds"
    (url-retrieve
     (format "https://api.github.com/repos/%s/%s/issues/%s" owner repo num)
     (lambda (status)
       (let ((title (unless (plist-get status :error)
                      (goto-char url-http-end-of-headers)
                      (gethash "title" (json-parse-buffer)))))
         (kill-buffer)
         (unless title
  	 (message "Couldn't fetch title for %s" url))
         (funcall callback title)))
     nil t))

  (defun my/gh/item (url callback)
    "Fetch the title of issue and call callback if valid title is found"
    (unless (string-match
             "github\\.com/\\([^/]+\\)/\\([^/]+\\)/\\(?:pull\\|issues\\)/\\([0-9]+\\)" url)
      (user-error "Not a GitHub pull request or issue URL: %s" url))
    (my/gh/issue-or-pull-title (match-string 1 url) (match-string 2 url) (match-string 3 url) callback))

  (defun my/org-insert-gh-item-at-point (url)
    "Insert \"- TITLE: URL\" for the GitHub pull request or issue at URL."
    (interactive
     (list (read-string "GitHub URL: " (current-kill 0 t))))
    (let ((marker (point-marker)))
      (my/gh/item
       url
       (lambda (title)
         (with-current-buffer (marker-buffer marker)
           (save-excursion
             (goto-char marker)
             (insert (format "%s: %s" title url))))))))

  (evil-define-key '(normal visual motion) 'global
    (kbd "<leader>og") #'my/org-insert-gh-item-at-point)
#+end_src
** Biweekly report emails
*** Helpers to generate email contents
#+begin_src emacs-lisp
  (require 'denote-journal)

  (defvar my/report-days 14
    "Number of days the report covers, counting today.")
  (defvar my/report-heading "BeagleBoard"
    "Journal heading whose contents go into the report.")

  (defun my/journal-files-for (time)
    "Return denote-journal files whose identifier falls on TIME's date.
  Signal an error if `denote-journal-directory' is not set."
    (sort (denote-journal--get-entry time 'daily)))

  (defun my/journal-section (time)
    "Return the body of `my/report-heading' in the journal entry for TIME, or nil."
    (mapcar
     (lambda (file)
       (denote--file-with-temp-buffer file
         (delay-mode-hooks (org-mode))
         (when-let ((pos (org-find-exact-headline-in-buffer my/report-heading)))
  	 (goto-char pos)
  	 (string-trim (org-get-entry)))))
     (my/journal-files-for time)))

  (defun my/journal-days (days)
    "Generate sequence of time for last `days` days"
    (mapcar
     (lambda (idx)
       (time-subtract
        (current-time)
        (days-to-time idx)))
     (number-sequence (- days 1) 0 -1)))

  (defun my/journal-report (days)
    (mapcar
     (lambda (time)
       (format "* %s\n%s\n\n"
  	     (format-time-string "%B %d" time)
  	     (string-join (my/journal-section time))))
     (my/journal-days days)))

  (defun my/biweekly-report ()
    "Collect the BeagleBoard sections of the last `days' days."
    (string-join (my/journal-report 14)))
#+end_src

*** Compose function
#+begin_src emacs-lisp
  (defun my/mail-biweekly-report ()
    "Compose the biweekly work report from the denote-journal entries."
    (interactive)
    (let* ((days  (my/journal-days 14))
           (fmt   "%d %b")
           (body  (my/biweekly-report)))
      (message-mail (string-join '("Jason Kridner <jkridner@beagleboard.org>"
                               "christi@beagleboard.org"
                               "lorforlinux@beagleboard.org")
                             ", ")
                (format "Biweekly report: %s – %s"
                        (format-time-string fmt (car days))
                        (format-time-string fmt (car (last days))))
                `(("From" . "Ayush Singh <ayush@beagleboard.org>")
                  ("Cc"   . ,(string-join '("kathy.giori@beagleboard.org"
                                            "robertcnelson@gmail.com"
                                            "drew@beagleboard.org"
                                            "markayoder@beagleboard.org")
                                          ", "))))
      (message-goto-body)
      (save-excursion (insert body))))
#+end_src

** Monthly invoices
*** Helper to rename denote files to a better format
- Only enabled for fircs/invoices, but should be useful when adding almost any denote named file.
#+begin_src emacs-lisp
  (require 'mml)
  (require 'denote)

  (defun my/invoice-filename (fname)
    "Return a simplified filename for a Denote invoice or FIRC FNAME.
  Return nil if FNAME is not a Denote file with the keyword
  \"invoice\" or \"firc\"."
    (when (stringp fname)
      (let ((title (denote-retrieve-filename-title fname))
            (keyword (denote-retrieve-filename-keywords fname)))
        (when (and title (member keyword '("invoice" "firc")))
          (format "%s-%s.%s"
                  (upcase keyword)
                  (upcase title)
                  (file-name-extension fname))))))

  (defun my/invoices--add-recipient-filename (args)
    "Add a recipient-filename to attachment tags of invoices and FIRCs.
  ARGS are the arguments of `mml-insert-empty-tag'."
    (let ((name (and (eq (car args) 'part)
                     (my/invoice-filename (plist-get (cdr args) 'filename)))))
      (if name
          (append args (list 'recipient-filename name))
        args)))

  (advice-add 'mml-insert-empty-tag :filter-args #'my/invoices--add-recipient-filename)
#+end_src
*** Montly invoice generator function
#+begin_src emacs-lisp
  (defun my/invoice-for-month (year month)
    "All invoices/fircs for month"
    (directory-files
     (expand-file-name "invoices" denote-directory)
     t
     (format "\\`%04d%02d.*\\.pdf\\'" year month)))

  (defun my/invoices-mail-last-month ()
    "Compose a mail with last month's invoices and FIRCs attached.
  A file belongs to a month by its Denote identifier."
    (interactive)
    (let* ((now (decode-time))
           ;; Day 0 of this month is the last day of the previous one.
           (last-month (encode-time (list 0 0 0 0 (decoded-time-month now)
                                          (decoded-time-year now) nil -1 nil)))
           (decoded (decode-time last-month))
           (files (my/invoice-for-month (decoded-time-year decoded)
                                        (decoded-time-month decoded))))
      (unless files
        (user-error "No invoices or FIRCs for %s"
                    (format-time-string "%B %Y" last-month)))
      (message-mail "Jawalshah3@yahoo.com"
                    (format-time-string "Invoice and FIRC for %B %Y" last-month)
                    `(("From" . ,"Ayush Singh <ayushsingh1325@gmail.com>")))
      (message-goto-body)
      (save-excursion
        (dolist (f files)
          (mml-attach-file f "application/pdf" nil "attachment")))))
#+end_src
** Sync Notes
- I have a systemd service (with daily timer) to sync my notes. Here, we just add a helper to sync
  on emacs entry and exit as well
#+begin_src emacs-lisp
  (defun my/notes-sync (&optional wait)
    "Start the notes sync service on the host. With WAIT, block until it finishes."
    (let ((args '("--host" "systemctl" "--user" "start" "notes-sync.service")))
      (if wait
          (apply #'call-process "flatpak-spawn" nil nil nil args)
        (apply #'start-process "notes-sync" nil "flatpak-spawn" args))))

  (add-hook 'emacs-startup-hook #'my/notes-sync)
  (add-hook 'kill-emacs-hook (lambda () (my/notes-sync t)))
#+end_src

* Dired
#+begin_src emacs-lisp
  (setq dired-dwim-target t)
  (add-hook 'dired-mode-hook #'auto-revert-mode)
#+end_src
